export default {
  login: "EricChukoltyansky",
  id: 78796215,
  node_id: "MDQ6VXNlcjc4Nzk2MjE1",
  avatar_url: "https://fs.knesset.gov.il/globaldocs/MK/1/1_1_2_3.png?v=111",
  gravatar_id: "",
  url: "https://api.github.com/users/EricChukoltyansky",
  html_url: "https://github.com/EricChukoltyansky",
  followers_url: "https://api.github.com/users/EricChukoltyansky/followers",
  following_url:
    "https://api.github.com/users/EricChukoltyansky/following{/other_user}",
  gists_url: "https://api.github.com/users/EricChukoltyansky/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/EricChukoltyansky/starred{/owner}{/repo}",
  subscriptions_url:
    "https://api.github.com/users/EricChukoltyansky/subscriptions",
  organizations_url: "https://api.github.com/users/EricChukoltyansky/orgs",
  repos_url: "https://api.github.com/users/EricChukoltyansky/repos",
  events_url: "https://api.github.com/users/EricChukoltyansky/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/EricChukoltyansky/received_events",
  type: "User",
  site_admin: false,
  name: "Yuli Edelstein",
  company: null,
  blog: "",
  location: "Israel",
  email: null,
  hireable: null,
  bio: null,
  twitter_username: "YuliEdelstein",
  public_repos: 32,
  public_gists: 0,
  followers: 3,
  following: 9,
  created_at: "2021-02-09T11:13:08Z",
  updated_at: "2021-11-18T11:49:53Z",
};
